site_name: LayoutUtil
site_description: Documentation for LayoutUtil
site_author: Nickuhhh
site_url: https://nickuhhh.github.io/LayoutUtil/

repo_name: LayoutUtil
repo_url: https://github.com/Nickuhhh/LayoutUtil

nav:
  - Home: index.md
  - Plugin: plugin.md
  - Installation: installation.md
  - Easy Mistakes: mistakes.md
  - Examples: examples.md
  - API: api.md

theme:
  name: material
  palette:
    scheme: slate
    primary: light blue
    accent: light blue
  hljs_languages:
    - lua

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: true